See ChangeLog

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -890,15 +890,16 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-logdir=DIR	  set fidogate log DIR
-  --with-vardir=DIR	  set fidogate var DIR
-  --with-spooldir=DIR	  set fidogate spool DIR
-  --with-sysconfdir=DIR     set fidogate config DIR
-  --with-btbasedir=DIR	  set fidogate BTBASE DIR
-  --with-netmaildir=DIR	  set fidogate NETMAIL DIR
-  --with-newsbindir=DIR	  set INN bin directory
-  --with-inews=PATH	  set directory containt INEWS
-  --with-rnews=PATH	  set directory containt RNEWS
+  --with-logdir=DIR		set fidogate log DIR
+  --with-vardir=DIR		set fidogate var DIR
+  --with-lockdir=DIR		set fidogate lock DIR
+  --with-spooldir=DIR		set fidogate spool DIR
+  --with-sysconfdir=DIR		set fidogate config DIR
+  --with-btbasedir=DIR		set fidogate BTBASE DIR
+  --with-netmaildir=DIR		set fidogate NETMAIL DIR
+  --with-newsbindir=DIR		set INN bin directory
+  --with-inews=PATH		set directory containt INEWS
+  --with-rnews=PATH		set directory containt RNEWS
   --without-news          build fidogate without news server
   --without-rsf           build fidogate without runinc send_fidogate function
   --with-sendmail=PATH    Specify path to sendmail
@@ -1349,6 +1350,21 @@ esac
 
 fi;
 
+# Check for a --with-lockdir argument
+
+# Check whether --with-lockdir or --without-lockdir was given.
+if test "${with_lockdir+set}" = set; then
+  withval="$with_lockdir"
+  case "$with_lockdir" in
+yes) { { echo "$as_me:$LINENO: error: --with-lockdir requires an argument; use --with-lockdir=DIR" >&5
+echo "$as_me: error: --with-lockdir requires an argument; use --with-lockdir=DIR" >&2;}
+   { (exit 1); exit 1; }; } ;;
+''|no) ;;
+*) LOCKDIR="$withval" ;;
+esac
+
+fi;
+
 # Check for a --with-spooldir argument
 
 # Check whether --with-spooldir or --without-spooldir was given.
@@ -1415,7 +1431,7 @@ esac
 
 fi;
 if ! test "${netmaildir+set}" = set; then
-    netmaildir='/var/spool/fido/bt/netmail'
+    netmaildir="${btbasedir}/netmail"
 fi
 
 
@@ -3556,7 +3572,7 @@ test x"$silent" = xyes && libtool_flags="$libtool_flags --silent"
 case "$host" in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3559 "configure"' > conftest.$ac_ext
+  echo '#line 3575 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5072,8 +5088,8 @@ fi
 
 echo "$as_me:$LINENO: checking for lock directory" >&5
 echo $ECHO_N "checking for lock directory... $ECHO_C" >&6
-if test -d /var/lock; then
-	LOCKDIR=/var/lock/fidogate
+if test "${with_lockdir+set}" = set; then
+	LOCKDIR="$with_lockdir"
 elif test -d /var/run; then
 	LOCKDIR=/var/run/fidogate
 elif test -d /var/spool/lock; then
